# Generated by Django 4.1.5 on 2023-01-28 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='correctOption',
            new_name='correct_option',
        ),
    ]
